name: Update Pronote WebCAL

on:
  schedule:
    # Exécution toutes les 15 min de 5h00 à 7h45 UTC (7h-9h+ en France) du lundi au vendredi
    - cron: '*/15 5-7 * * 1-5'  
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          PRONOTE_URL: ${{ secrets.PRONOTE_URL }}
          PRONOTE_USERNAME: ${{ secrets.PRONOTE_USERNAME }}
          PRONOTE_PASSWORD: ${{ secrets.PRONOTE_PASSWORD }}
          FREE_USER: ${{ secrets.FREE_USER }}
          FREE_PASS: ${{ secrets.FREE_PASS }}
          ICS_URL: "https://joelafrite421/pronote-calendar/luce.ics"
        run: python script.py

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Envoie la racine avec luce.ics généré

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
